title: "Saad Ijaz"
baseurl: ""

first-name: 'Saad'
last-name: 'Ijaz'
job-title: 'Machine Learning Developer'
profpic: '/resources/img/profilepic.jpg'
profpic-retina: '/resources/img/profilepic@2x.jpg'
email: 'saadijaz@outlook.com'
github: 'saadijaz1'
location: 'Calgary, AB, Canada'
location-url: "https://goo.gl/maps/tTXYvHFQ9rj6GyiLA"

# For syntax highlighting, the primary programming langauge you intend to use in
# blog articles. By default, Google's prettify will be used for this programming
# language, as per the instructions here: https://github.com/google/code-prettify
# For example, if I indicate `scala`, all pre/code blocks will have the `lang-scala`
# class added to the markup, triggering prettify to highlight the syntax as Scala.
primarylanguage: python
# To sidestep the default language for syntax highlighting set here, you can be
# explicit in your blog articles with the langauge you'd prefer to use. E.g.,
# <pre>
#   <code class="prettyprint lang-ruby">
#    ..ruby code here...
#   </code>
# </pre>

# categories:
#   blog:
#     permalink: /blog/:title.html

# Settings for blog RSS feed
name: "Saad Ijaz"
description: "Hello! I am Saad, a proud alumnus of the Texas A&M University. I am passionate about technology and dedicated to delivering excellence in Machine Learning. I aim to make a positive impact in the tech industry, and I am excited to continue growing and learning alongside my talented colleagues at Aimsio."
url: "https://github.com/saadijaz1"
tagline: "Saad Ijaz Page, Machine Learning Developer"

permalink: /:categories/:title.html
# markdown: redcarpet
highlighter: null

sass:
  style: compressed

livereload: true

plugins:
  - jekyll-seo-tag


social:
  name: Saad Ijaz
  links:
    - https://www.linkedin.com/in/saadijaz1/
    - https://github.com/saadijaz1


remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one